export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const EDITUSER_REQUEST = 'EDITUSER_REQUEST';
export const EDITUSER_SUCCESS = 'EDITUSER_SUCCESS';
export const EDITUSER_FAILURE = 'EDITUSER_FAILURE';
